version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 35000:5432
    environment:
      POSTGRES_PASSWORD: pawme
      POSTGRES_USER : pawme
      POSTGRES_DB : pawmedb
